name: Test

on:
  [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
      - name: Running unit tests
        run: yarn test
