name: Deploy to GitHub Pages
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Install dependencies
      uses: bahmutov/npm-install@v1
    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: lbenie/reading-time-estimator
        TARGET_BRANCH: master
        BUILD_SCRIPT: yarn build && yarn build:docs
        BUILD_DIR: docs
